# Generated by Django 4.2.8 on 2023-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Paid at"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                default="created", max_length=255, verbose_name="Status"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "item")},
        ),
    ]
