# Generated by Django 4.2.8 on 2023-12-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_order_paid_at_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("usd", "USD"), ("eur", "EUR")],
                default="usd",
                max_length=255,
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                ],
                default="created",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
