# Generated by Django 4.2.8 on 2023-12-21 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_item_currency_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="currency",
        ),
    ]
